import type { Door, FurnitureType, ItemDefinition, Room, Window } from "./types";

export const DEFAULT_ROOM: Room = {
  width: 4000,
  height: 3000,
  wallThickness: 200,
  ceilingHeight: 2400,
  gridSize: 100,
  snapEnabled: true,
  displayUnit: "mm",
};

// Legacy support - will be deprecated
export const FURNITURE_CATALOG: Record<
  FurnitureType,
  { label: string; width: number; depth: number; height: number }
> = {
  bed: { label: "침대", width: 2000, depth: 1500, height: 500 },
  desk: { label: "책상", width: 1200, depth: 600, height: 720 },
  chair: { label: "의자", width: 450, depth: 450, height: 900 },
  closet: { label: "수납장", width: 1200, depth: 600, height: 2000 },
  sofa: { label: "소파", width: 1800, depth: 900, height: 800 },
  table: { label: "테이블", width: 1200, depth: 800, height: 750 },
  refrigerator: { label: "냉장고", width: 800, depth: 700, height: 1800 },
  "washing-machine": { label: "세탁기", width: 600, depth: 650, height: 850 },
  dryer: { label: "건조기", width: 600, depth: 650, height: 850 },
  dishwasher: { label: "식기세척기", width: 600, depth: 600, height: 850 },
  oven: { label: "오븐", width: 600, depth: 600, height: 600 },
  microwave: { label: "전자레인지", width: 500, depth: 400, height: 300 },
  tv: { label: "TV", width: 1200, depth: 100, height: 700 },
  "air-conditioner": { label: "에어컨", width: 900, depth: 300, height: 300 },
  "air-purifier": { label: "공기청정기", width: 400, depth: 400, height: 700 },
  humidifier: { label: "가습기", width: 300, depth: 300, height: 500 },
  sink: { label: "싱크대", width: 1800, depth: 600, height: 850 },
  toilet: { label: "변기", width: 500, depth: 700, height: 400 },
  bathtub: { label: "욕조", width: 1600, depth: 800, height: 600 },
  shower: { label: "샤워부스", width: 900, depth: 900, height: 2100 },
};

// New unified item catalog with search support
export const ITEM_CATALOG: ItemDefinition[] = [
  // ===== Furniture - Beds =====
  {
    id: "bed-single",
    type: "bed",
    category: "furniture",
    label: "싱글 침대",
    name: "싱글 침대",
    width: 1000,
    depth: 2000,
    height: 500,
    tags: ["침대", "침실", "싱글"],
    keywords: ["bed", "single", "침대", "1인"],
  },
  {
    id: "bed-super-single",
    type: "bed",
    category: "furniture",
    label: "슈퍼싱글 침대",
    name: "슈퍼싱글 침대",
    width: 1100,
    depth: 2000,
    height: 500,
    tags: ["침대", "침실", "슈퍼싱글"],
    keywords: ["bed", "super single", "침대", "슈퍼싱글"],
  },
  {
    id: "bed-double",
    type: "bed",
    category: "furniture",
    label: "더블 침대",
    name: "더블 침대",
    width: 1400,
    depth: 2000,
    height: 500,
    tags: ["침대", "침실", "더블"],
    keywords: ["bed", "double", "침대", "2인"],
  },
  {
    id: "bed-queen",
    type: "bed",
    category: "furniture",
    label: "퀸 침대",
    name: "퀸 침대",
    width: 1500,
    depth: 2000,
    height: 500,
    tags: ["침대", "침실", "퀸"],
    keywords: ["bed", "queen", "침대", "퀸사이즈"],
  },
  {
    id: "bed-king",
    type: "bed",
    category: "furniture",
    label: "킹 침대",
    name: "킹 침대",
    width: 1650,
    depth: 2050,
    height: 500,
    tags: ["침대", "침실", "킹"],
    keywords: ["bed", "king", "침대", "킹사이즈"],
  },
  {
    id: "bed-family",
    type: "bed",
    category: "furniture",
    label: "패밀리 침대",
    name: "패밀리 침대",
    width: 1800,
    depth: 2100,
    height: 500,
    tags: ["침대", "침실", "패밀리"],
    keywords: ["bed", "family", "침대", "가족용"],
  },

  // ===== Furniture - Desks =====
  {
    id: "desk-compact",
    type: "desk",
    category: "furniture",
    label: "컴팩트 책상",
    name: "컴팩트 책상",
    width: 1000,
    depth: 600,
    height: 720,
    tags: ["책상", "서재", "컴팩트"],
    keywords: ["desk", "compact", "책상", "작은"],
  },
  {
    id: "desk-standard",
    type: "desk",
    category: "furniture",
    label: "스탠다드 책상",
    name: "스탠다드 책상",
    width: 1400,
    depth: 700,
    height: 720,
    tags: ["책상", "서재", "스탠다드"],
    keywords: ["desk", "standard", "책상", "일반"],
  },
  {
    id: "desk-wide",
    type: "desk",
    category: "furniture",
    label: "와이드 책상",
    name: "와이드 책상",
    width: 1800,
    depth: 800,
    height: 720,
    tags: ["책상", "서재", "와이드"],
    keywords: ["desk", "wide", "책상", "넓은"],
  },

  // ===== Furniture - Chairs =====
  {
    id: "chair-dining",
    type: "chair",
    category: "furniture",
    label: "식탁 의자",
    name: "식탁 의자",
    width: 450,
    depth: 500,
    height: 900,
    tags: ["의자", "주방", "식탁"],
    keywords: ["chair", "dining", "의자", "식탁"],
  },
  {
    id: "chair-office",
    type: "chair",
    category: "furniture",
    label: "사무 의자",
    name: "사무 의자",
    width: 520,
    depth: 520,
    height: 1000,
    tags: ["의자", "서재", "사무"],
    keywords: ["chair", "office", "의자", "사무실"],
  },
  {
    id: "chair-lounge",
    type: "chair",
    category: "furniture",
    label: "라운지 체어",
    name: "라운지 체어",
    width: 700,
    depth: 800,
    height: 900,
    tags: ["의자", "거실", "라운지"],
    keywords: ["chair", "lounge", "의자", "안락"],
  },

  // ===== Furniture - Closets =====
  {
    id: "closet-single",
    type: "closet",
    category: "furniture",
    label: "1자 수납장",
    name: "1자 수납장",
    width: 1200,
    depth: 600,
    height: 2200,
    tags: ["수납", "침실", "1자"],
    keywords: ["closet", "wardrobe", "수납장", "옷장", "1자"],
  },
  {
    id: "closet-double",
    type: "closet",
    category: "furniture",
    label: "2자 수납장",
    name: "2자 수납장",
    width: 1800,
    depth: 600,
    height: 2200,
    tags: ["수납", "침실", "2자"],
    keywords: ["closet", "wardrobe", "수납장", "옷장", "2자"],
  },
  {
    id: "closet-built-in",
    type: "closet",
    category: "furniture",
    label: "붙박이장",
    name: "붙박이장",
    width: 2400,
    depth: 650,
    height: 2300,
    tags: ["수납", "침실", "붙박이"],
    keywords: ["closet", "built-in", "수납장", "옷장", "붙박이"],
  },

  // ===== Furniture - Sofas =====
  {
    id: "sofa-1",
    type: "sofa",
    category: "furniture",
    label: "1인 소파",
    name: "1인 소파",
    width: 900,
    depth: 900,
    height: 850,
    tags: ["소파", "거실", "1인"],
    keywords: ["sofa", "couch", "소파", "1인용"],
  },
  {
    id: "sofa-2",
    type: "sofa",
    category: "furniture",
    label: "2인 소파",
    name: "2인 소파",
    width: 1600,
    depth: 900,
    height: 850,
    tags: ["소파", "거실", "2인"],
    keywords: ["sofa", "couch", "소파", "2인용"],
  },
  {
    id: "sofa-3",
    type: "sofa",
    category: "furniture",
    label: "3인 소파",
    name: "3인 소파",
    width: 2000,
    depth: 950,
    height: 850,
    tags: ["소파", "거실", "3인"],
    keywords: ["sofa", "couch", "소파", "3인용"],
  },
  {
    id: "sofa-4",
    type: "sofa",
    category: "furniture",
    label: "4인 소파",
    name: "4인 소파",
    width: 2400,
    depth: 1000,
    height: 850,
    tags: ["소파", "거실", "4인"],
    keywords: ["sofa", "couch", "소파", "4인용"],
  },

  // ===== Furniture - Tables =====
  {
    id: "table-2",
    type: "table",
    category: "furniture",
    label: "2인 식탁",
    name: "2인 식탁",
    width: 800,
    depth: 800,
    height: 750,
    tags: ["테이블", "주방", "2인"],
    keywords: ["table", "dining", "식탁", "테이블", "2인"],
  },
  {
    id: "table-4",
    type: "table",
    category: "furniture",
    label: "4인 식탁",
    name: "4인 식탁",
    width: 1400,
    depth: 800,
    height: 750,
    tags: ["테이블", "주방", "4인"],
    keywords: ["table", "dining", "식탁", "테이블", "4인"],
  },
  {
    id: "table-6",
    type: "table",
    category: "furniture",
    label: "6인 식탁",
    name: "6인 식탁",
    width: 1800,
    depth: 850,
    height: 750,
    tags: ["테이블", "주방", "6인"],
    keywords: ["table", "dining", "식탁", "테이블", "6인"],
  },
  {
    id: "table-round",
    type: "table",
    category: "furniture",
    label: "원형 4인 테이블",
    name: "원형 4인 테이블",
    width: 1100,
    depth: 1100,
    height: 750,
    tags: ["테이블", "주방", "원형"],
    keywords: ["table", "dining", "round", "식탁", "테이블", "원형"],
  },

  // ===== Appliances - Kitchen =====
  {
    id: "refrigerator-standard",
    type: "refrigerator",
    category: "appliance",
    label: "일반 냉장고",
    name: "일반 냉장고",
    width: 700,
    depth: 700,
    height: 1800,
    tags: ["냉장고", "주방", "가전"],
    keywords: ["refrigerator", "fridge", "냉장고", "주방가전"],
  },
  {
    id: "refrigerator-large",
    type: "refrigerator",
    category: "appliance",
    label: "대형 냉장고",
    name: "대형 냉장고",
    width: 900,
    depth: 750,
    height: 1850,
    tags: ["냉장고", "주방", "가전", "대형"],
    keywords: ["refrigerator", "fridge", "냉장고", "주방가전", "양문형"],
  },
  {
    id: "washing-machine",
    type: "washing-machine",
    category: "appliance",
    label: "세탁기",
    name: "세탁기",
    width: 600,
    depth: 650,
    height: 850,
    tags: ["세탁기", "세탁실", "가전"],
    keywords: ["washing machine", "washer", "세탁기"],
  },
  {
    id: "dryer",
    type: "dryer",
    category: "appliance",
    label: "건조기",
    name: "건조기",
    width: 600,
    depth: 650,
    height: 850,
    tags: ["건조기", "세탁실", "가전"],
    keywords: ["dryer", "건조기"],
  },
  {
    id: "dishwasher",
    type: "dishwasher",
    category: "appliance",
    label: "식기세척기",
    name: "식기세척기",
    width: 600,
    depth: 600,
    height: 850,
    tags: ["식기세척기", "주방", "가전"],
    keywords: ["dishwasher", "식기세척기", "주방가전"],
  },
  {
    id: "oven-standard",
    type: "oven",
    category: "appliance",
    label: "오븐",
    name: "오븐",
    width: 600,
    depth: 600,
    height: 600,
    tags: ["오븐", "주방", "가전"],
    keywords: ["oven", "오븐", "주방가전"],
  },
  {
    id: "microwave",
    type: "microwave",
    category: "appliance",
    label: "전자레인지",
    name: "전자레인지",
    width: 500,
    depth: 400,
    height: 300,
    tags: ["전자레인지", "주방", "가전"],
    keywords: ["microwave", "전자레인지", "주방가전"],
  },

  // ===== Electronics =====
  {
    id: "tv-50",
    type: "tv",
    category: "electronics",
    label: "50인치 TV",
    name: "50인치 TV",
    width: 1120,
    depth: 100,
    height: 650,
    tags: ["TV", "거실", "전자제품"],
    keywords: ["tv", "television", "티비", "50인치"],
  },
  {
    id: "tv-65",
    type: "tv",
    category: "electronics",
    label: "65인치 TV",
    name: "65인치 TV",
    width: 1450,
    depth: 100,
    height: 840,
    tags: ["TV", "거실", "전자제품"],
    keywords: ["tv", "television", "티비", "65인치"],
  },
  {
    id: "air-conditioner",
    type: "air-conditioner",
    category: "electronics",
    label: "벽걸이 에어컨",
    name: "벽걸이 에어컨",
    width: 900,
    depth: 300,
    height: 300,
    tags: ["에어컨", "냉난방", "전자제품"],
    keywords: ["air conditioner", "ac", "에어컨", "냉방"],
  },
  {
    id: "air-purifier",
    type: "air-purifier",
    category: "electronics",
    label: "공기청정기",
    name: "공기청정기",
    width: 400,
    depth: 400,
    height: 700,
    tags: ["공기청정기", "전자제품"],
    keywords: ["air purifier", "공기청정기"],
  },
  {
    id: "humidifier",
    type: "humidifier",
    category: "electronics",
    label: "가습기",
    name: "가습기",
    width: 300,
    depth: 300,
    height: 500,
    tags: ["가습기", "전자제품"],
    keywords: ["humidifier", "가습기"],
  },

  // ===== Fixtures - Bathroom/Kitchen =====
  {
    id: "sink-kitchen",
    type: "sink",
    category: "fixture",
    label: "주방 싱크대",
    name: "주방 싱크대",
    width: 1800,
    depth: 600,
    height: 850,
    tags: ["싱크대", "주방", "수전"],
    keywords: ["sink", "kitchen sink", "싱크대", "주방"],
  },
  {
    id: "toilet",
    type: "toilet",
    category: "fixture",
    label: "변기",
    name: "변기",
    width: 500,
    depth: 700,
    height: 400,
    tags: ["변기", "화장실", "수전"],
    keywords: ["toilet", "변기", "화장실"],
  },
  {
    id: "bathtub",
    type: "bathtub",
    category: "fixture",
    label: "욕조",
    name: "욕조",
    width: 1600,
    depth: 800,
    height: 600,
    tags: ["욕조", "화장실", "수전"],
    keywords: ["bathtub", "욕조", "화장실"],
  },
  {
    id: "shower-booth",
    type: "shower",
    category: "fixture",
    label: "샤워부스",
    name: "샤워부스",
    width: 900,
    depth: 900,
    height: 2100,
    tags: ["샤워", "화장실", "수전"],
    keywords: ["shower", "샤워부스", "샤워실", "화장실"],
  },
];

// Legacy support
export type FurniturePreset = {
  id: string;
  label: string;
  type: FurnitureType;
  name: string;
  width: number;
  depth: number;
  height: number;
};

export const FURNITURE_PRESETS: FurniturePreset[] = ITEM_CATALOG.map((item) => ({
  id: item.id,
  label: item.label,
  type: item.type,
  name: item.name,
  width: item.width,
  depth: item.depth,
  height: item.height,
}));

export const DEFAULT_DOOR: Omit<Door, "id" | "wall" | "offset"> = {
  width: 900,
  height: 2100,
  hinge: "left",
  swing: "inward",
  openAngle: 90,
  thickness: 40,
};

export const DEFAULT_WINDOW: Omit<Window, "id" | "wall" | "offset"> = {
  width: 1200,
  height: 1200,
  sillHeight: 900,
};

// Search utility
export function searchItems(query: string): ItemDefinition[] {
  if (!query.trim()) {
    return ITEM_CATALOG;
  }

  const lowerQuery = query.toLowerCase().trim();
  return ITEM_CATALOG.filter((item) => {
    // Search in label
    if (item.label.toLowerCase().includes(lowerQuery)) return true;
    // Search in name
    if (item.name.toLowerCase().includes(lowerQuery)) return true;
    // Search in tags
    if (item.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))) return true;
    // Search in keywords
    if (item.keywords.some((kw) => kw.toLowerCase().includes(lowerQuery))) return true;
    return false;
  });
}

// Category labels
export const CATEGORY_LABELS: Record<string, string> = {
  furniture: "가구",
  appliance: "가전제품",
  electronics: "전자제품",
  fixture: "설비",
};
